[package]
name = "authorizer"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.2"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
